spring.datasource.url=jdbc:postgresql://localhost:5432/telegram
spring.datasource.username=postgres
spring.datasource.password=1234
spring.liquibase.change-log=classpath:liquibase/changelog.yml

telegram.bot.name=GalinaNotificationsBot
telegram.bot.token=7518460105:AAESeHeQwn5PNA4bnWK01iCFaF4mpqS7wCY